name: Lint

on:
  push:
    paths:
      - '**.py'
      - 'requirements.txt'
      - '**/.github/workflows/*.y*ml'
  pull_request:
    paths:
      - '**.py'
      - 'requirements.txt'
      - '**/.github/workflows/*.y*ml'

jobs:
  lint:
    name: "Lint"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@v4.2.2"

        - name: "Set up Python"
          uses: actions/setup-python@v5.6.0
          with:
            python-version: "3.12"
            cache: "pip"

        - name: "Install requirements"
          run: python3 -m pip install -r requirements.txt

        - name: "Lint"
          run: python3 -m ruff check ./custom_components/audiobookshelf

        - name: Run MyPy
          run: python3 -m mypy custom_components/audiobookshelf

        - name: "Format"
          run: python3 -m ruff format ./custom_components/audiobookshelf --check
